"""update institute table

Revision ID: 920c93ff9687
Revises: b0324bf755cf
Create Date: 2024-04-27 11:56:12.675530

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "920c93ff9687"
down_revision: Union[str, None] = "b0324bf755cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("institute_id", sa.UUID(), nullable=True))
    op.alter_column("posts", "company_id", existing_type=sa.UUID(), nullable=True)
    op.create_foreign_key(
        "fk_post_institute_id",
        "posts",
        "institutes",
        ["institute_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_post_institute_id", "posts", type_="foreignkey")
    op.alter_column("posts", "company_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("posts", "institute_id")
    # ### end Alembic commands ###
