"""add event relationships

Revision ID: b8b419adc779
Revises: 778fe0cc96e7
Create Date: 2024-04-27 15:04:47.530683

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8b419adc779"
down_revision: Union[str, None] = "778fe0cc96e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("company_id", sa.UUID(), nullable=True))
    op.add_column("events", sa.Column("institute_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_event_company_id",
        "events",
        "companies",
        ["company_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_event_institute_id",
        "events",
        "institutes",
        ["institute_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_event_company_id", "events", type_="foreignkey")
    op.drop_constraint("fk_event_institute_id", "events", type_="foreignkey")
    op.drop_column("events", "institute_id")
    op.drop_column("events", "company_id")
    # ### end Alembic commands ###
