"""add unique on user email

Revision ID: c664c61aea2d
Revises: c90b7b1b575a
Create Date: 2024-04-27 10:19:09.287084

"""

from typing import Sequence, Union

from alembic import op

revision: str = "c664c61aea2d"
down_revision: Union[str, None] = "c90b7b1b575a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uix_user_email", "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_user_email", "users", type_="unique")
    # ### end Alembic commands ###
