"""add posts table

Revision ID: c90b7b1b575a
Revises: 07cfd1b2fb40
Create Date: 2024-04-27 01:40:29.639743

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c90b7b1b575a"
down_revision: Union[str, None] = "07cfd1b2fb40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("start_dt", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("end_dt", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("responsibilities", sa.String(), nullable=False),
        sa.Column("requirements", sa.String(), nullable=False),
        sa.Column("salary", sa.String(), nullable=False),
        sa.Column("documents", sa.String(), nullable=False),
        sa.Column("deadline", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("recruiter_contacts", sa.String(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "create_dt",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("update_dt", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("posts")
    # ### end Alembic commands ###
